services:
    cloudflared:
        image: cloudflare/cloudflared:latest
        container_name: cloudflared
        restart: unless-stopped
        command: tunnel run
        environment:
           - TZ=Europe/Berlin
           - TUNNEL_TOKEN=${TUNNEL_TOKEN}

networks:
    default:
    external:
       name: bridge-net

