---
- name: Check if Docker is installed
  command: "docker --version"
  register: docker_check
  ignore_errors: yes

- name: Install Docker
  shell: "curl -o- https://get.docker.com | sh -x"
  args:
    chdir: /tmp
  when: docker_check.rc != 0

- name: Enable and start Docker daemon
  systemd:
    name: docker
    enabled: yes
    state: started