---
- name: Update dependencies
  apt:
    name: '*'
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Install essential packages
  package:
    name: '{{ packages }}'
    state: latest
